### ISSUE TITLE
[緊急]學長幫個忙呀!!

### ISSUE THREAD

**Issue by madeuf** [lebr0nli/bookroll_pdf_downloader#1]
學長好! 我是今年剛進來的大一菜雞，不知道學長畢業了沒，

在github找到了這酷東西，後天就要會考了，現在很需要辣些微積分考古題，
但使用google collab執行時出現了以下問題(附圖)，
在本機執行時也在這一步時停止，好像是.get_text()出了點問題，
霸脫幫我看看是哪裡出了問題，我真的很不想要用手機開bookroll寫考古啊啊啊qwq

![image](https://user-images.githubusercontent.com/90695324/159178331-a3e27348-10fd-49e9-be0f-2eca084a9c74.png)

**Comment by lebr0nli** [comment]
嗨，我還沒畢業XD
我猜這個問題應該是因爲課程id不一樣，所以導致沒有讀到正確的東西
請問你現在微積分課程預覽頁面的網址的`view.php?id=`後面的數字還是一樣是`48`嗎？
(因為之前我沒有下載其他堂課教材的需求，我id是直接寫死的)
如果不是的話，可以幫我將`view.php?id=48`的`48`改成你那堂課的id，或許這樣就能解決了!

還有我的bookroll帳號已經看不到這堂課的教材了，加上這又是我很久以前寫的dirty code，所以debug起來可能會有點困難XD
如果真的想要修好這個工具的話可能需要跟你借一下帳號，我有空時再嘗試看看把它修好

不過在這之前，如果你很急，而且也不需要批量下載的話，你有試過我的另一個[chrome extension](https://github.com/lebr0nli/bookroll-extension)嗎？
剛剛我有測試一下，這個extension貌似還能用，應該可以應急一下

**Comment by madeuf** [comment]
確實，id變成407了。
我有去下載了那個chrome插件，成功下載了考古。
我只能說學長真是多才多藝 👍 

能在github上能隨便找到同校學生寫的程式，也是緣分了吧xd
辛苦啦! 希望這個插件能繼續傳承下去~
我會跟朋朋分享這個好東西的

P.S. 插件中的某個東東好像要過期了，只能用到2023的樣子
![image](https://user-images.githubusercontent.com/90695324/159300897-99c2b060-f524-4c61-a931-49cf2fc55140.png)

**Comment by lebr0nli** [comment]
> 確實，id變成407了。 

了解，感謝測試! 

> 我有去下載了那個chrome插件，成功下載了考古。 

很高興我的插件有幫助到你，祝你考試順利!

> P.S. 插件中的某個東東好像要過期了，只能用到2023的樣子

好的，我已經更新到Manifest V3了，謝謝回報!
